# Generated by Django 4.2.18 on 2025-02-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_api', '0002_userdetails_delete_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='firstname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='lastname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
