# Generated by Django 4.2.18 on 2025-02-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_api', '0006_savedrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedrecipe',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
